mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: com.moonlight.one.domain
server:
  port: 80
spring:
  profiles:
    active: datasource  #加载 以-datasource结尾的配置文件
  main:
    banner-mode: off
